version: "3.7"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      # Required to sync file changes.
      - .:/app
      # Required to not break node modules.
      - /app/node_modules
      # Required for next to do it's thing.
      - /app/.next
